(cl:in-package volta_msgs-msg)
(cl:export '(LOWBATTERY_FLAG-VAL
          LOWBATTERY_FLAG
          CHARGING_FLAG-VAL
          CHARGING_FLAG
          MOTOR_ALARM_FLAG-VAL
          MOTOR_ALARM_FLAG
          BMS_ALARM_FLAG-VAL
          BMS_ALARM_FLAG
          HIGH_TEMP_FLAG-VAL
          HIGH_TEMP_FLAG
          COMM_ERROR_FLAG-VAL
          COMM_ERROR_FLAG
          BMS_SOC-VAL
          BMS_SOC
          BMS_SOH-VAL
          BMS_SOH
          BMS_VOLTAGE-VAL
          BMS_VOLTAGE
          BMS_CURRENT-VAL
          BMS_CURRENT
          BMS_VOLTAGEDIFF-VAL
          BMS_VOLTAGEDIFF
          BMS_TEMPDIFF-VAL
          BMS_TEMPDIFF
          BMS_BCUMODE-VAL
          BMS_BCUMODE
          BMS_ALARM-VAL
          BMS_ALARM
          M_STATE-VAL
          M_STATE
          M_ALARM-VAL
          M_ALARM
          M_POWER-VAL
          M_POWER
          M_VOLTAGE-VAL
          M_VOLTAGE
          M_CURRENT-VAL
          M_CURRENT
          M_COMM-VAL
          M_COMM
          RELAY_TEMP-VAL
          RELAY_TEMP
          POWERCONN_TEMP-VAL
          POWERCONN_TEMP
          PRECHARGE_TEMP-VAL
          PRECHARGE_TEMP
          POWER_SUPPLY_TEMP-VAL
          POWER_SUPPLY_TEMP
          BATTERY_IN_VOLT-VAL
          BATTERY_IN_VOLT
          PRE_CHARGE_VOLT-VAL
          PRE_CHARGE_VOLT
          HW_ESTOP_VOLT-VAL
          HW_ESTOP_VOLT
          SW_ESTOP_VOLT-VAL
          SW_ESTOP_VOLT
          MOTOR_ALARM_CODE-VAL
          MOTOR_ALARM_CODE
          MOTOR_FUN_FAIL-VAL
          MOTOR_FUN_FAIL
          M_INIT-VAL
          M_INIT
          M_CW-VAL
          M_CW
          M_CCW-VAL
          M_CCW
          M_STOP-VAL
          M_STOP
          M_BREAK-VAL
          M_BREAK
          M_SETRPM-VAL
          M_SETRPM
          M_GETRPM-VAL
          M_GETRPM
          M_PARAM-VAL
          M_PARAM
          M_ALARM-VAL
          M_ALARM
          PRECHARGE_FUSE-VAL
          PRECHARGE_FUSE
          MOTOR_FUSE-VAL
          MOTOR_FUSE
          LED_STATE-VAL
          LED_STATE
))