(cl:in-package volta_msgs-msg)
(cl:export '(SOC-VAL
          SOC
          SOH-VAL
          SOH
          CURRENT-VAL
          CURRENT
          VOLTAGE-VAL
          VOLTAGE
          SYSTEM_STATUS-VAL
          SYSTEM_STATUS
          RELAY_TEMP-VAL
          RELAY_TEMP
          POWE_IN_TEMP-VAL
          POWE_IN_TEMP
          MOTOR_VOLT-VAL
          MOTOR_VOLT
          BATTERY_VOLT-VAL
          BATTERY_VOLT
          HW_ESTOP_VOLT-VAL
          HW_ESTOP_VOLT
          MOTORALARM-VAL
          MOTORALARM
          DIAG_EN-VAL
          DIAG_EN
          HW_ESTOP_STATE-VAL
          HW_ESTOP_STATE
          SW_ESTOP_STATE-VAL
          SW_ESTOP_STATE
          ROS_ESTOP_STATE-VAL
          ROS_ESTOP_STATE
))