// Generated by gencpp from file volta_msgs/BMS.msg
// DO NOT EDIT!


#ifndef VOLTA_MSGS_MESSAGE_BMS_H
#define VOLTA_MSGS_MESSAGE_BMS_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace volta_msgs
{
template <class ContainerAllocator>
struct BMS_
{
  typedef BMS_<ContainerAllocator> Type;

  BMS_()
    : soc(0.0)
    , soh(0.0)
    , current(0.0)
    , voltage(0.0)  {
    }
  BMS_(const ContainerAllocator& _alloc)
    : soc(0.0)
    , soh(0.0)
    , current(0.0)
    , voltage(0.0)  {
  (void)_alloc;
    }



   typedef float _soc_type;
  _soc_type soc;

   typedef float _soh_type;
  _soh_type soh;

   typedef float _current_type;
  _current_type current;

   typedef float _voltage_type;
  _voltage_type voltage;





  typedef boost::shared_ptr< ::volta_msgs::BMS_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::volta_msgs::BMS_<ContainerAllocator> const> ConstPtr;

}; // struct BMS_

typedef ::volta_msgs::BMS_<std::allocator<void> > BMS;

typedef boost::shared_ptr< ::volta_msgs::BMS > BMSPtr;
typedef boost::shared_ptr< ::volta_msgs::BMS const> BMSConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::volta_msgs::BMS_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::volta_msgs::BMS_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::volta_msgs::BMS_<ContainerAllocator1> & lhs, const ::volta_msgs::BMS_<ContainerAllocator2> & rhs)
{
  return lhs.soc == rhs.soc &&
    lhs.soh == rhs.soh &&
    lhs.current == rhs.current &&
    lhs.voltage == rhs.voltage;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::volta_msgs::BMS_<ContainerAllocator1> & lhs, const ::volta_msgs::BMS_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace volta_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::volta_msgs::BMS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::volta_msgs::BMS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volta_msgs::BMS_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::volta_msgs::BMS_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volta_msgs::BMS_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::volta_msgs::BMS_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::volta_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e5d0e1c804606ac58f230d85fba314ed";
  }

  static const char* value(const ::volta_msgs::BMS_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe5d0e1c804606ac5ULL;
  static const uint64_t static_value2 = 0x8f230d85fba314edULL;
};

template<class ContainerAllocator>
struct DataType< ::volta_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "volta_msgs/BMS";
  }

  static const char* value(const ::volta_msgs::BMS_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::volta_msgs::BMS_<ContainerAllocator> >
{
  static const char* value()
  {
    return "float32 soc\n"
"float32 soh\n"
"float32 current\n"
"float32 voltage\n"
;
  }

  static const char* value(const ::volta_msgs::BMS_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::volta_msgs::BMS_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.soc);
      stream.next(m.soh);
      stream.next(m.current);
      stream.next(m.voltage);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BMS_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::volta_msgs::BMS_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::volta_msgs::BMS_<ContainerAllocator>& v)
  {
    s << indent << "soc: ";
    Printer<float>::stream(s, indent + "  ", v.soc);
    s << indent << "soh: ";
    Printer<float>::stream(s, indent + "  ", v.soh);
    s << indent << "current: ";
    Printer<float>::stream(s, indent + "  ", v.current);
    s << indent << "voltage: ";
    Printer<float>::stream(s, indent + "  ", v.voltage);
  }
};

} // namespace message_operations
} // namespace ros

#endif // VOLTA_MSGS_MESSAGE_BMS_H
